---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alsadigt/public_html/
#    - /bin/cp <file_name> $DEPLOYPATH #Copy specific file to destination from root
    - /bin/cp /mhb-test/ $DEPLOYPATH #copy specific file from source sub folder
#    - /bin cp * $DEPLOYPATH #copy all from root
    - /bin cp /mhb-test/* $DEPLOYPATH #copy all from sub folder root